language: python
install:
  - pip install prance flex
script:
  - python test/test.py
  - prance validate --strict oai.json oai_stoplight.json oai.yaml

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms: $SLACK_TOKEN
